### ISSUE TITLE
Ramp-up for adding AuthN/AuthZ to Helium

### ISSUE THREAD

**Issue by aka-msft** [aka-msft/helium#2]
# Description
Initial ramp-up to prepare for authentication/authorization scenario in Helium (will be forked after v1 is complete).

# Tasks
Documentation:
- [ ] AAD (Terminology: directories, tenants, etc.): https://docs.microsoft.com/en-us/previous-versions/azure/azure-services/jj573650(v=azure.100)
- [ ] OAuth and OpenID Connect
- [ ] Scenario: Protecting a Web API: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview
- [ ] JWT tokens (id tokens and access tokens): https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens
- [ ] Azure AD passport-js: https://github.com/AzureAD/passport-azure-ad

# Done
Sufficient understanding of AAD and related concepts to effectively implement security for Helium.
