### ISSUE TITLE
Code samples - review and practice

### ISSUE THREAD

**Issue by aka-msft** [aka-msft/helium#3]
## Description
Review code samples from the links below.  Clone and attempt to run and test these examples to learn how AAD is integrated to protect a web API.

## Tasks
Clone and run:
- [ ] AAD Node Web API: https://github.com/Azure-Samples/active-directory-node-webapi
- [ ] ExpressJS Passport (best practices example): https://github.com/maliksahil/expressjs-passport-azure-ad
- [ ] OIDCStrategy vs BearerStrategy: https://github.com/AzureAD/passport-azure-ad#5-usage

## Done
Gain experience using AAD to secure a web API by successfully implementing the above (and other) code samples related to Helium.
