### ISSUE TITLE
Implement AuthN/AuthZ for Helium using AAD

### ISSUE THREAD

**Issue by aka-msft** [aka-msft/helium#4]
## Description
After Helium v1 is complete, update repository and add authentication and authorization to API endpoints.

## Tasks
- [ ] Fork/update helium repo
- [ ] Establish requirements for groups and users that can access each Helium endpoint and verb (GET, POST, DELETE, etc.)
- [ ] Create groups + users in AAD (admin + regular users)
- [ ] Create a config file to map users to endpoints/verbs they're allowed access to
- [ ] Create middleware that checks if the user's token is valid and whether they have access to the endpoint/verb.
- [ ] Write tests for secured endpoints

## Done
All Helium endpoints are secured with AAD, and tests are in place to verify security of endpoints.
